Rewrite of the NametagPlus module
AwesomePossum212/nametag-plus pull request #22
Opened 2021-10-26 06:39 UTC by Water261

This rewrites the module using some new Luau features, like typechecking. It changes the config[instanceName] to config.defaults[instanceName] and just tidies up the code a little.

2021-11-07 16:34 UTC, AwesomePossum212 commented
Sorry for the late response! I'll take a look at this once you reopen it. Thanks for helping out!

2021-11-07 20:24 UTC, Water261 commented
It's no problem, I need to get it properly working in Studio first.

2021-11-10 01:22 UTC, Water261 commented
Alright, now it should work. The issue was that I forgot to assign the frame a parent and therefore it wouldn't show up and just caused errors.

2021-11-10 01:43 UTC, Water261 commented
When merging, can you squash and merge so I don't litter the commit history.

2021-11-10 01:57 UTC, Water261 commented
Just squashed it on my side to stop it from littering my commit history. No need to squash now.

2021-11-10 02:09 UTC, Water261 commented
Uh yeah, I'm not the best when it comes to git. This was me rebasing stuff. So fun.

2021-11-10 02:12 UTC, Water261 commented
This adds variadic support as well.

2021-11-10 07:05 UTC, Water261 commented
Alrighty, everything is finished and ready to be merged.

changeTag is now a variadic function to identify what should be changed you set the Name property inside the props table to the object you want to change.

2021-11-17 01:26 UTC, AwesomePossum212 commented
Thank you so much! I'll review and approve this ASAP (there are a lot of changes though, so it could take some time).

2021-11-17 01:35 UTC, AwesomePossum212 commented on .github/README.md
> +local nametagConfig = require(game:GetService("ReplicatedStorage"):FindFirstChild("NametagModule").Configuration)
Thanks for cleaning up the mistakes!

2021-11-17 01:40 UTC, AwesomePossum212 commented on src/Configuration.lua
> +	ZIndex = 2,
Thanks for tidying up all of the commas and leading zeroes!

2021-11-17 01:42 UTC, AwesomePossum212 commented on src/init.lua
> +local function changeTag(tag: BillboardGui, ...): nil
much appreciated

2021-11-17 01:43 UTC, AwesomePossum212 approved these changes
Looks good! I'll need to test it in Studio and make a few minor changes before merging, but this is a huge step towards modernizing Nametag+.

2021-12-04 17:30 UTC, AwesomePossum212 requested changes
Could you either add back waitForProperty or code in a workaround? This was originally added to allow the server to give players nametags as soon as they joined, even before their name is loaded in.

2021-12-04 17:30 UTC, AwesomePossum212 commented on src/init.lua
> +		local finalName = utils.waitForProperty(player, "Name")
It looks like this function was removed from Utilities. Could you either add it back to Utilities or find a work around here? Whenever I try to call addTag in Studio this line errors.

2021-12-04 17:30 UTC, AwesomePossum212 commented on src/init.lua
> +		local finalName = utils.waitForProperty(player, "Name")
Another instance of waitForProperty.

2021-12-04 21:48 UTC, Water261 commented
Yeah I'll add it back, I initially removed it and VSCode didn't through any syntax errors.

2021-12-04 21:53 UTC, Water261 commented
Alright, all problems have been fixed.

2021-12-10 00:56 UTC, AwesomePossum212 approved these changes
Tested and it works!

2021-12-10 00:57 UTC, merged